In [ ]:
import pandas as pd

In [69]:
df = pd.read_csv("pmdata/p01/pmsys/srpe.csv")
df.head(10)

,end_date_time,activity_names,perceived_exertion,duration_min
0,2019-11-05T22:51:54.710Z,"['individual', 'running']",7,30
1,2019-11-11T21:15:15.092Z,"['individual', 'running']",6,30
2,2019-11-14T21:00:53.000Z,"['team', 'soccer']",7,60
3,2019-11-18T21:34:44.995Z,"['individual', 'endurance']",6,50
4,2019-11-21T21:06:25.146Z,"['team', 'soccer']",6,70
5,2019-11-23T09:34:50.739Z,"['individual', 'running']",8,30
6,2019-11-26T08:03:56.794Z,"['individual', 'running']",7,40
7,2019-11-28T21:07:17.918Z,"['team', 'soccer']",6,60
8,2019-12-03T08:13:07.418Z,"['individual', 'running']",6,40
9,2019-12-05T22:00:26.647Z,"['team', 'soccer']",6,60

In [70]:
df["activity_names"].value_counts()          # eyeball the distinct values first
df[df["activity_names"].str.contains(",")]     # any multi-code days?

,end_date_time,activity_names,perceived_exertion,duration_min
0,2019-11-05T22:51:54.710Z,"['individual', 'running']",7,30
1,2019-11-11T21:15:15.092Z,"['individual', 'running']",6,30
2,2019-11-14T21:00:53.000Z,"['team', 'soccer']",7,60
3,2019-11-18T21:34:44.995Z,"['individual', 'endurance']",6,50
4,2019-11-21T21:06:25.146Z,"['team', 'soccer']",6,70
5,2019-11-23T09:34:50.739Z,"['individual', 'running']",8,30
6,2019-11-26T08:03:56.794Z,"['individual', 'running']",7,40
7,2019-11-28T21:07:17.918Z,"['team', 'soccer']",6,60
8,2019-12-03T08:13:07.418Z,"['individual', 'running']",6,40
9,2019-12-05T22:00:26.647Z,"['team', 'soccer']",6,60
10,2019-12-26T13:51:11.843Z,"['individual', 'running']",6,30
11,2020-01-03T07:01:52.220Z,"['individual', 'running']",7,30
12,2020-01-04T09:15:46.446Z,"['individual', 'running']",6,50
13,2020-01-07T06:30:05.000Z,"['individual', 'running']",6,30
14,2020-01-09T21:18:09.000Z,"['team', 'soccer']",6,60
15,2020-01-14T07:00:47.513Z,"['individual', 'running']",7,30
16,2020-01-16T19:48:47.892Z,"['team', 'soccer']",5,80
17,2020-01-18T07:47:48.673Z,"['individual', 'running']",6,50
18,2020-01-23T20:51:44.108Z,"['team', 'soccer']",6,70
19,2020-01-25T11:30:34.000Z,"['individual', 'running']",6,40
20,2020-01-30T20:06:54.418Z,"['team', 'soccer']",6,90
21,2020-02-05T06:55:08.631Z,"['individual', 'running']",7,40
22,2020-02-06T07:24:58.415Z,"['individual', 'running']",6,30
23,2020-02-06T20:04:08.608Z,"['team', 'soccer']",6,80
24,2020-02-10T20:25:33.415Z,"['individual', 'running']",7,30
25,2020-02-13T06:33:07.907Z,"['individual', 'running']",5,30
26,2020-02-21T07:14:11.786Z,"['individual', 'running']",5,20
27,2020-02-21T09:42:39.000Z,"['individual', 'running']",5,20
28,2020-02-26T07:14:39.669Z,"['individual', 'running']",5,30
29,2020-02-27T20:00:31.075Z,"['team', 'soccer']",7,80
30,2020-03-05T19:47:49.316Z,"['team', 'soccer']",6,70
31,2020-03-05T21:00:22.000Z,"['individual', 'running']",5,30
32,2020-03-10T07:07:40.601Z,"['individual', 'running']",5,40
33,2020-03-14T08:45:18.557Z,"['individual', 'running']",6,30

In [71]:
df["activity_names"].value_counts()

activity_names
['individual', 'running']      22
['team', 'soccer']             11
['individual', 'endurance']     1
Name: count, dtype: int64

In [72]:
df["activity_names"].apply(lambda s: len(eval(s))).value_counts()

activity_names
2    34
Name: count, dtype: int64

In [73]:
(df.isnull().mean() * 100).round(2)

end_date_time         0.0
activity_names        0.0
perceived_exertion    0.0
duration_min          0.0
dtype: float64

end_date_time and activity_names could be the primary keys here.
activity_names are lists containing individual / team sport and the actual activity

In [26]:
df.info()            # dtypes + null counts
df.nunique()         # is 'activity type' 5 values or 500?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   end_date_time       34 non-null     object
 1   activity_names      34 non-null     object
 2   perceived_exertion  34 non-null     int64
 3   duration_min        34 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.2+ KB

end_date_time         34
activity_names         3
perceived_exertion     4
duration_min           8
dtype: int64

In [11]:
df.describe()        # numeric ranges - does RPE really sit 1–10?

       perceived_exertion  duration_min
count           34.000000     34.000000
mean             6.088235     45.882353
std              0.753483     19.712732
min              5.000000     20.000000
25%              6.000000     30.000000
50%              6.000000     40.000000
75%              6.750000     60.000000
max              8.000000     90.000000

RPE sits between 5-8

In [39]:
df = pd.read_csv("pmdata/p02/pmsys/injury.csv")
df.head(10)

       effective_time_frame                                           injuries
0  2019-11-13T13:53:01.675Z  {'left_elbow': 'minor', 'right_shoulder': 'min...
1  2019-11-18T08:25:08.190Z                                                 {}
2  2019-11-25T09:55:48.301Z                                                 {}
3  2019-12-04T21:05:19.186Z                                                 {}
4  2020-02-08T16:28:19.484Z                                                 {}

Injury is in set, shows which body part and grades the extent of the injury

In [40]:
df[df['injuries'].notnull()]

       effective_time_frame                                           injuries
0  2019-11-13T13:53:01.675Z  {'left_elbow': 'minor', 'right_shoulder': 'min...
1  2019-11-18T08:25:08.190Z                                                 {}
2  2019-11-25T09:55:48.301Z                                                 {}
3  2019-12-04T21:05:19.186Z                                                 {}
4  2020-02-08T16:28:19.484Z                                                 {}

In [33]:
(df.isnull().mean() * 100).round(2)

effective_time_frame    0.0
injuries                0.0
dtype: float64

In [62]:
df = pd.read_csv("pmdata/p01/pmsys/wellness.csv")
df.head(10)

,effective_time_frame,fatigue,mood,readiness,sleep_duration_h,sleep_quality,soreness,soreness_area,stress
0,2019-11-01T08:31:40.751Z,2,3,5,6,3,2,[12921003],3
1,2019-11-02T10:00:01.229Z,2,3,6,6,3,2,[12921003],3
2,2019-11-03T14:28:03.263Z,3,3,8,6,3,3,[],3
3,2019-11-04T07:05:28.429Z,3,3,8,6,3,3,[],3
4,2019-11-05T06:13:35.998Z,3,3,8,5,3,3,[],3
5,2019-11-06T07:13:02.320Z,3,3,5,5,3,2,"[48979004, 32696007]",3
6,2019-11-07T06:39:25.426Z,3,3,7,5,3,3,[],3
7,2019-11-08T09:05:09.558Z,3,3,7,6,3,3,[],3
8,2019-11-09T08:00:27.364Z,3,3,8,6,3,3,[],3
9,2019-11-10T20:38:08.787Z,3,3,7,6,3,3,[],3

Wellness shows timestamp and their scores. What is soreness_area?

In [63]:
df["date"] = pd.to_datetime(df["effective_time_frame"]).dt.date   # strip time → calendar day
counts = df.groupby("date").size()
counts[counts > 1]

Series([], dtype: int64)

In [64]:
df["soreness_area"].value_counts()          # eyeball the distinct values first
df[df["soreness_area"].str.contains(",")]     # any multi-code days?

,effective_time_frame,fatigue,mood,readiness,sleep_duration_h,sleep_quality,soreness,soreness_area,stress,date
5,2019-11-06T07:13:02.320Z,3,3,5,5,3,2,"[48979004, 32696007]",3,2019-11-06
10,2019-11-12T07:33:27.703Z,2,3,4,6,3,2,"[48979004, 32696007]",3,2019-11-12
13,2019-11-15T05:38:25.987Z,2,3,5,6,3,2,"[48979004, 32696007, 12921003]",3,2019-11-15
17,2019-11-19T06:31:46.844Z,2,3,5,5,2,2,"[48979004, 32696007, 12921003]",3,2019-11-19
20,2019-11-22T06:00:11.205Z,2,3,4,5,3,2,"[48979004, 32696007, 12921003]",3,2019-11-22
23,2019-11-25T07:04:27.705Z,2,3,7,5,3,2,"[48979004, 32696007, 12921003]",3,2019-11-25
25,2019-11-27T07:50:27.161Z,2,3,5,5,3,2,"[48979004, 32696007, 12921003]",3,2019-11-27
32,2019-12-04T08:31:12.920Z,2,3,5,5,2,2,"[48979004, 32696007]",3,2019-12-04
34,2019-12-06T07:02:10.649Z,2,3,3,4,2,2,"[48979004, 32696007, 12921003]",3,2019-12-06
49,2019-12-27T08:50:24.996Z,2,3,4,7,2,2,"[48979004, 32696007]",3,2019-12-27
50,2019-12-28T19:34:52.387Z,2,3,5,6,2,2,"[48979004, 32696007, 12921003]",3,2019-12-28
51,2019-12-29T08:41:48.839Z,2,3,6,6,3,2,"[48979004, 32696007, 12921003]",3,2019-12-29
52,2019-12-30T08:17:11.894Z,2,3,6,5,3,2,"[48979004, 32696007]",3,2019-12-30
56,2020-01-04T09:17:04.540Z,2,2,5,7,3,2,"[48979004, 12921003]",3,2020-01-04
57,2020-01-06T05:25:40.497Z,2,3,5,5,2,2,"[48979004, 32696007, 12921003]",2,2020-01-06
59,2020-01-08T11:23:48.712Z,2,2,6,5,2,2,"[48979004, 32696007, 12921003]",2,2020-01-08
66,2020-01-15T05:39:20.077Z,3,3,4,6,3,2,"[48979004, 32696007, 12921003]",3,2020-01-15
68,2020-01-17T06:58:30.205Z,3,3,6,6,3,2,"[48979004, 32696007]",3,2020-01-17
69,2020-01-18T08:04:31.262Z,3,3,7,5,3,2,"[48979004, 32696007]",3,2020-01-18
70,2020-01-19T08:38:03.384Z,2,3,4,6,3,2,"[48979004, 32696007, 12921003]",3,2020-01-19
71,2020-01-20T08:33:26.650Z,3,3,5,6,3,2,"[48979004, 32696007, 12921003]",2,2020-01-20
75,2020-01-24T12:21:58.499Z,3,3,4,6,3,2,"[48979004, 32696007, 12921003]",3,2020-01-24
81,2020-01-31T05:36:15.867Z,1,3,3,5,3,2,"[48979004, 32696007, 12921003]",3,2020-01-31
87,2020-02-06T07:31:26.341Z,3,3,6,5,3,2,"[48979004, 32696007, 12921003]",3,2020-02-06
88,2020-02-07T05:55:30.958Z,2,3,3,5,2,1,"[48979004, 32696007, 12921003]",3,2020-02-07
89,2020-02-08T09:08:21.547Z,2,3,5,7,3,2,"[48979004, 32696007, 12921003]",3,2020-02-08
93,2020-02-12T09:38:23.865Z,2,3,7,5,2,2,"[48979004, 32696007]",3,2020-02-12
95,2020-02-14T08:02:26.929Z,1,3,3,4,2,2,"[48979004, 32696007, 12921003]",3,2020-02-14
102,2020-02-22T08:00:35.086Z,2,3,5,6,3,2,"[48979004, 32696007, 12921003]",3,2020-02-22
107,2020-02-27T09:00:16.666Z,2,3,6,5,3,2,"[48979004, 32696007]",3,2020-02-27
108,2020-02-28T08:02:27.747Z,2,3,3,5,2,2,"[48979004, 32696007, 12921003]",3,2020-02-28
111,2020-03-02T05:44:55.857Z,2,3,3,6,3,2,"[48979004, 32696007, 12921003, 22943007]",3,2020-03-02
112,2020-03-03T06:53:52.028Z,3,3,6,6,3,2,"[12921003, 22943007, 368208006, 368209003]",3,2020-03-03
115,2020-03-06T09:15:18.645Z,2,3,2,6,2,1,"[48979004, 32696007, 12921003, 22943007]",3,2020-03-06
123,2020-03-15T22:48:57.301Z,2,3,4,5,2,2,"[48979004, 32696007, 12921003]",3,2020-03-15
124,2020-03-16T06:52:28.674Z,2,3,6,5,2,2,"[48979004, 32696007, 12921003]",3,2020-03-16

In [35]:
(df.isnull().mean() * 100).round(2)

effective_time_frame    0.0
fatigue                 0.0
mood                    0.0
readiness               0.0
sleep_duration_h        0.0
sleep_quality           0.0
soreness                0.0
soreness_area           0.0
stress                  0.0
dtype: float64